# Generated by Django 4.2.6 on 2023-10-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninstallment',
            name='pay_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
