# Generated by Django 4.2.6 on 2023-10-16 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('social_name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('address_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
            ],
            options={
                'verbose_name': 'Base Client',
                'verbose_name_plural': 'Base Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=18)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('user_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physical Client',
                'verbose_name_plural': 'Physical Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_registration', models.CharField(blank=True, max_length=200)),
                ('municipal_registration', models.CharField(blank=True, max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('user_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Client',
                'verbose_name_plural': 'Legal Clients',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('balance', models.FloatField()),
                ('agency', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=20)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativa', models.BooleanField()),
                ('client', models.ManyToManyField(to='core.client')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
