# Generated by Django 4.2.6 on 2023-10-27 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ManyToManyField(to='core.client'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
        migrations.AlterField(
            model_name='card',
            name='banner',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='situation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
