# Generated by Django 4.2.6 on 2023-11-16 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientlegal_cnpj_alter_account_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ramal',
        ),
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approval_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 16), null=True),
        ),
    ]
