# Generated by Django 4.2.6 on 2023-10-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_client_clientphysical_clientlegal_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlegal',
            name='user_cnpj',
        ),
        migrations.RemoveField(
            model_name='clientphysical',
            name='user_cpf',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=8)),
                ('admin_tax', models.FloatField()),
                ('deadline', models.CharField(max_length=20)),
                ('risk_degree', models.CharField(max_length=5)),
                ('profitability', models.DecimalField(decimal_places=2, max_digits=8)),
                ('finished', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('ramal', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacao', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
            ],
        ),
    ]
