# Generated by Django 4.2.6 on 2023-10-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_clientlegal_user_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_interest', models.FloatField()),
                ('approved', models.BooleanField()),
                ('number_installments', models.IntegerField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ativa',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='observacao',
            new_name='observation',
        ),
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='contribution',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='profitability',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pay_day', models.DateField()),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
    ]
