# Generated by Django 4.2.6 on 2023-11-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_id_alter_loan_approval_date'),
        ('core', '0003_remove_contact_ramal_alter_client_picture_and_more'),
    ]

    operations = [
    ]
