# Generated by Django 4.2.6 on 2023-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_account_transfer_account_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='limit_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
