# Generated by Django 4.2.6 on 2023-11-29 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_card_limit_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ManyToManyField(null=True, to='core.client'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approval_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 29), null=True),
        ),
    ]
